try{
    run_continue();
} catch {
    console.log("run_continue not exists");
}
